title: DTS-AAC
description: Dataset of Telegraphic Synthesis for Augmentative and Alternative Communication
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions